import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import {evaluateSkateStatusRecord,nextChicagoDayStart,msUntilNextChicagoDay,type SkateStatusRecord} from '../client/src/lib/skateStatus.ts';
import {createSkateStatusSsr,SkateStatusSsrArtifactError} from '../server/skateStatusSsr.ts';
const record:SkateStatusRecord={state:'altered',note:'Academy only',updated:'2026-10-01',covered_from:'2026-09-28',covered_through:'2026-10-03',source_url:'https://example.com/academy'};
for(const [instant,current] of [['2026-10-04T04:59:59.999Z',true],['2026-10-04T05:00:00Z',false],['2026-10-01T04:59:59Z',false],['2026-10-01T05:00:00Z',true]] as const)test('Covered date '+instant,()=>assert.equal(evaluateSkateStatusRecord('rink',record,new Date(instant))?.isCurrent,current));
for(const [instant,next] of [['2026-03-08T06:00:00Z','2026-03-09T05:00:00Z'],['2026-11-01T05:00:00Z','2026-11-02T06:00:00Z'],['2026-10-04T04:59:59.999Z','2026-10-04T05:00:00Z']] as const)test('Chicago midnight '+instant,()=>{assert.equal(nextChicagoDayStart(new Date(instant))?.toISOString(),new Date(next).toISOString());assert.equal(msUntilNextChicagoDay(new Date(instant)),Date.parse(next)-Date.parse(instant)+250);});
for(const [name,override] of Object.entries({legacy:{covered_from:undefined},impossible:{covered_through:'2026-02-31'},reverse:{covered_from:'2026-10-04'},futureUpdated:{updated:'2026-10-02'},futureCoverage:{covered_from:'2026-10-02'},badState:{state:'maybe'},badUpdated:{updated:'soon'},stale:{updated:'2026-09-01'}}))test('Neutral '+name,()=>assert.equal(evaluateSkateStatusRecord('rink',{...record,...override},new Date('2026-10-01T12:00:00Z'))?.isCurrent,false));
test('Invalid clock',()=>assert.equal(evaluateSkateStatusRecord('rink',record,new Date(NaN))?.isCurrent,false));
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'isi-status-'));const ssr=path.join(dir,'ssr');fs.mkdirSync(ssr);fs.writeFileSync(path.join(dir,'package.json'),'{"type":"module"}');fs.writeFileSync(path.join(ssr,'status-routes.json'),'["/rink/example"]');fs.writeFileSync(path.join(ssr,'template.html'),'<!doctype html><html><head></head><body><div id="root"></div></body></html>');fs.writeFileSync(path.join(ssr,'entry-ssr.js'),'export function render(){return {html:"<p>Fresh status</p>",head:{title:"test"}}}');return {dir,ssr};}
async function withServer(handler:any,run:(url:string)=>Promise<void>){const app=express();app.use(handler);app.use((_req,res)=>res.status(200).send('STALE FALLBACK'));const s=app.listen(0,'127.0.0.1');await new Promise<void>(r=>s.once('listening',r));const a=s.address();assert.ok(a&&typeof a==='object');try{await run('http://127.0.0.1:'+a.port);}finally{await new Promise<void>((r,j)=>s.close(e=>e?j(e):r()));}}
for(const [name,change] of Object.entries({missingBundle:(f:any)=>fs.unlinkSync(path.join(f.ssr,'entry-ssr.js')),legacy:(f:any)=>{fs.unlinkSync(path.join(f.ssr,'template.html'));fs.unlinkSync(path.join(f.ssr,'status-routes.json'));},partial:(f:any)=>fs.unlinkSync(path.join(f.ssr,'template.html')),badManifest:(f:any)=>fs.writeFileSync(path.join(f.ssr,'status-routes.json'),'null'),invalidJson:(f:any)=>fs.writeFileSync(path.join(f.ssr,'status-routes.json'),'{broken'),missingRoot:(f:any)=>fs.writeFileSync(path.join(f.ssr,'template.html'),'<head></head>OLD NOTICE'),duplicateRoot:(f:any)=>fs.writeFileSync(path.join(f.ssr,'template.html'),'<head></head><div id="root"></div><div id="root"></div>'),invalidRenderer:(f:any)=>fs.writeFileSync(path.join(f.ssr,'entry-ssr.js'),'export const x=1;')}))test('Fail closed '+name,async()=>{const f=fixture();try{change(f);await assert.rejects(createSkateStatusSsr({distDir:f.dir}),SkateStatusSsrArtifactError);}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});
test('Failed render503 never stale fallback',async()=>{const f=fixture();fs.writeFileSync(path.join(f.ssr,'entry-ssr.js'),'export function render(){throw new Error("fixture failed")}');try{await withServer(await createSkateStatusSsr({distDir:f.dir}),async url=>{const res=await fetch(url+'/rink/example');assert.equal(res.status,503);assert.equal(res.headers.get('cache-control'),'no-store');assert.ok(!(await res.text()).includes('STALE FALLBACK'));assert.equal((await fetch(url+'/other')).status,200);});}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});
test('Aliases redirect before static serving',async()=>{const f=fixture();try{await withServer(await createSkateStatusSsr({distDir:f.dir}),async url=>{for(const alias of ['/rink/example/','/rink/example/index.html','/rink/example/%69ndex.html']){const res=await fetch(url+alias+'?keep=1',{redirect:'manual'});assert.equal(res.status,301);assert.equal(res.headers.get('location'),'/rink/example?keep=1');}assert.ok((await(await fetch(url+'/rink/example')).text()).includes('Fresh status'));});}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});
test('Actual HTML expires advisory/FAQ without rebuild',async()=>{let now=new Date('2026-10-04T04:59:59Z');await withServer(await createSkateStatusSsr({distDir:path.resolve('dist'),now:()=>now}),async url=>{const route='/rink/centennial-sportsplex-nashville-tn';const before=await(await fetch(url+route)).text();assert.ok(before.includes('September 28 through October 3'));assert.ok(before.includes('nashvilleskatingacademycentennial.finnlyconnect.com/'));now=new Date('2026-10-04T05:00:00Z');const after=await(await fetch(url+route)).text();assert.ok(!after.includes('September 28 through October 3'));assert.ok(!after.includes('id="skate-status-centennial'));assert.ok(after.includes('2026-10-01'));assert.ok(after.includes('"lastReviewed":"2026-06-29"'));assert.ok(after.includes('levels/3485?facility_ids=4'));const hub=await(await fetch(url+'/city/tn/nashville')).text();assert.ok(!hub.includes('Academy: altered'));});});
